### ISSUE TITLE
To Release: oma 1.13

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/oma#181]
Targets and expectations for oma's 1.13 release.

New Features
---

- [x] APT/Ubuntu APT/Ubuntu Pro Pro `auth.conf.d` support  @eatradish (#109)
- [x] ~~Output hyphenation support @eatradish (#180)~~
- [x] [Topic Update Manifest](https://gist.github.com/MingcongBai/912e778216aad58cf504713dcd4898cc) support (#266)
- [x] Filter out WIP/draft/no-PR branches in `oma topics` @eatradish (#212)
     - May require changes in [topic-manifest](https://github.com/AOSC-Dev/repokit) cc @liushuyu
- [x] UI improvements
    - [x] TUI: Splitting out user actions from calculated actions in confirmation - to design @MingcongBai  cc @eatradish (#200)
    - [x] TUI: Support for a dedicated upgrade action key or interface @eatradish cc @black-desk  (#206)
    - [x] Implement a prettier "broken dependency" output @eatradish (#25)
    - [x] Add "resolving dependencies ..." progress spinner (#204) 
    - [x] Add oma pager key u and d support (#239) 
    - [x] Pedding UI add version diff color (#273)
- [x] Early check for duplicate source entries @eatradish (#193)
- [x] Add `oma upgrade --no-remove` option (`apt upgrade` equivalent) for non-AOSC OS targets @eatradish (#194)
- [x] Add `remove_config` (`--remove-config`) argument to `oma install` and `oma upgrade` @eatradish (#195)
- [x] Improve `multiarch` support (#208)
- [x] Download timeout feature (#244)
- [x] Add `oma-refresh` verify `Release` and `Release.gpg` support (#248)
- [x] `oma topics` failed will revert topic status and `sources.list`  (#252)
- [x] Log installed pacakge to `/var/lib/oma/installed` (#275)
- [x] Split `fix-broken` and `fix-dpkg-status` (#277)
- [ ] ~~Cache search index (#281)~~

Project Meta
---

- [x] Pre-commit hook @wxiwnd (#184)
- [ ] Code and documentation coverage @wxiwnd 
- [ ] Fluent catalog clean up @MingcongBai 
- [x] Update README @wxiwnd  @MingcongBai (https://github.com/AOSC-Dev/oma/pull/243)

Distribution Support
---

- [x] Linux Mint and Debian unstable @MingcongBai 
- [x] Non-x86 binaries

**Comment by eatradish** [comment]
v1.13.0 Released
