### ISSUE TITLE
To Release: oma 1.14

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/oma#311]
Targets and expectations for oma's 1.14 release.

New Features
---

- [ ] ~~Detail/Overview toggle for TUI confirmation~~
- [x] Check sources list file is supported (#322)

Behavioral Changes and Refactors
---

- [x] Correct handling for partially available (e.g., in mirror A but not in B) topics #301 
    - [x] Speed up sources.list writing while configuring topics (only check for topic availability while saving topics configuration)
- [x] Refactor `oma-fetch` error (#295)
   - [x] Downloading and display download error message

Project Meta
---

Distribution Support
---
